name: Melinda publish to npm

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    # if: contains(github.ref, 'refs/tags/')
    outputs:
      needs_to_publish: $${{ steps.script.outputs.needs_to_publish }}
    steps:
      - name: Checkout this code repository
        uses: actions/checkout@v5
      - name: Run script
        id: script
        run: ./script.sh
        env:
          PLUGIN_TAG_PATTERN: '6.0'
      - name: Test env
        if: ${{ env.NEEDS_TO_RUN == 'true' || env.NEEDS_TO_RUN == 'false'}}
        run: echo "We have need-to-run env"
      # Setup .npmrc file to publish to npm
      - name: Publish
        if: $${{ steps.script.outputs.needs_to_publish != 'false'}}
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd repo && npm install && npm run buildbinary && npm run buildpackage && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORACLEDB_ALEPH_NPM_TOKEN }}